- name: Install Webserver
  hosts: webservers
  gather_facts: false
  become: true

  tasks:
  - name: Install apache2 Package
    apt:
      name: apache2
      state: present
  - name: Change apache2 Port
    copy:
      src: ports.conf.tmpl
      dest: /etc/apache2/ports.conf
    notify: Restart apache2 Service

  handlers:
  - name: Restart apache2 Service
    service:
      name: apache2
      state: restarted
